### ISSUE TITLE
Updating marshal dependency

### ISSUE THREAD

**Issue by vasilak** [instore/rails-cookie-parser#2]
Any chance of updating `marshal` dependency soon?
I am specifically interested in support for `float`s.
Thanks.

**Comment by clayzermk1** [comment]
@vasilak would you mind bumping #1? I should be able to just bump the versions on that PR.

**Comment by clayzermk1** [comment]
marshal version bumped, PR updated.

**Comment by clayzermk1** [comment]
@vasilak please give https://github.com/clayzermk1/rails-cookie-parser/releases/tag/0.0.4 a go.

**Comment by clayzermk1** [comment]
@vasilak v0.0.5 published on npm https://www.npmjs.com/package/rails-cookie-parser/v/0.0.5

**Comment by vasilak** [comment]
@clayzermk1 Thanks for the update, the new version works fine 👍
